- name: Enable nfs-server service
  ansible.builtin.service:
    name: "{{ os_vars[ansible_facts['os_family']]['nfs']['server-service'] }}"
    enabled: yes
    state: restarted
  listen: "nfs-exportfs"

- name: nfs-exportfs
  command: exportfs -arv
  listen: "nfs-exportfs"

- name: daemon-reload
  command: systemctl daemon-reload
  listen: "mount-all"

- name: mount-all
  command: mount -a
  listen: "mount-all"

- name: allow-root-ssh-key
  shell: "cat /root/.ssh/id_ed25519.pub >> /root/.ssh/authorized_keys"
  listen: "allow-root-ssh-key"