nfs:
  exports:
    - { path: '/home', network: "{{ networks['storage'] }}" }
    - { path: '/root', network: "{{ networks['admin'] }}" }
    - { path: '/etc/slurm', network: "{{ networks['admin'] }}" }

os_vars:
  RedHat:
    nfs:
      server-package: [ nfs-utils ]
      server-service: nfs-server
      client-package: []

  Debian:
    nfs:
      server-package: [ nfs-kernel-server ]
      server-service: nfs-kernel-server
      client-package: [ nfs-common ]