
- name: enable-munge-service
  ansible.builtin.service:
    name: munge
    state: restarted
    enabled: yes
  listen: "enable-munge-service"

- name: enable-slurmdbd-service
  ansible.builtin.service:
    name: slurmdbd
    state: restarted
    enabled: yes
  listen: "enable-slurmdbd-service"
