
- name: enable-munge-service
  ansible.builtin.systemd:
    name: munge
    state: restarted
    enabled: yes
  listen: "enable-munge-service"

- name: enable-slurmdbd-service
  ansible.builtin.systemd:
    name: slurmdbd
    state: restarted
    enabled: yes
  when: "inventory_hostname == slurmctld_primary"
  listen: "enable-slurmdbd-service"

- name: enable-slurmctld-service
  ansible.builtin.systemd:
    name: slurmctld
    state: restarted
    enabled: yes
  listen: "enable-slurmctld-service"

- name: enable-slurmrestd-service
  ansible.builtin.systemd:
    name: slurmrestd
    state: restarted
    enabled: true
    daemon_reload: true
  listen: "enable-slurmrestd-service"

- name: enable-slurmd-service
  ansible.builtin.systemd:
    name: slurmd
    state: restarted
    enabled: true
    daemon_reload: true
  when: "'compute' in group_names"
  listen: "enable-slurmd-service"

- name: create-slurm-users-and-accounts
  command: /tmp/create_slurm_users_and_accounts
  listen: "create-slurm-users-and-accounts"
