- name: Setting Slurm primary_controller
  ansible.builtin.set_fact:
    slurmctld_primary: "{{ groups['slurmctld'][0] }}"

- name: Setting NFS server name
  ansible.builtin.set_fact:
    nfs_server: "{{ groups['nfsd'][0] }}"

- name: Wait for cloud-init to finish
  command: cloud-init status --wait
  changed_when: false
  register: status
  failed_when: status.rc != 0 and status.rc != 2

- name: Install packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items: [ "vim", "libuser", "tree", "nano" ]

- name: Install RedHat packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items: [ "epel-release" ]
  when: ansible_facts['os_family'] == "RedHat"

- name: "Create slurm user"
  ansible.builtin.user:
    name: slurm
    system: true
    create_home: false
    local: true
    uid: 444

- name: "Create /etc/slurm"
  ansible.builtin.file:
    path: /etc/slurm
    state: directory
    owner: slurm
    group: root
    mode: '0775'

- name: Enable powertools repository
  ansible.builtin.command: yum config-manager --set-enabled powertools
  changed_when: false
  when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == '8'

- name: Enable powertools repository
  ansible.builtin.command: yum config-manager --set-enabled crb
  changed_when: false
  when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == '9'

- name: "Creates /root/.ssh/config"
  ansible.builtin.template:
    src: root-ssh-config.jinja2
    dest: /root/.ssh/config
    owner: root
    group: root
    mode: "0640"


- name: Install pdsh
  ansible.builtin.include_tasks:
    file: pdsh.yml
  tags: [ 'install-pdsh' ]