
- name: Wait for cloud-init to finish
  command: cloud-init status --wait
  changed_when: false
  register: status
  failed_when: status.rc != 0 and status.rc != 2

- name: Install packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items: [ "vim", "libuser", "tree", "nano" ]

- name: Install RedHat packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items: [ "epel-release" ]
  when: ansible_facts['os_family'] == "RedHat"

- name: Enable powertools repository
  ansible.builtin.command: yum config-manager --set-enabled powertools
  changed_when: false
  when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == 8

- name: Enable powertools repository
  ansible.builtin.command: yum config-manager --set-enabled crb
  changed_when: false
  when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == 9

- name: "Creates /root/.ssh/config"
  ansible.builtin.template:
    src: root-ssh-config.jinja2
    dest: /root/.ssh/config
    owner: root
    group: root
    mode: "0640"


- name: Install pdsh
  ansible.builtin.include_tasks:
    file: pdsh.yml
  tags: [ 'install-pdsh' ]